### PR TITLE
Add click_action for ionic FCM plugin

### PR DESCRIPTION
**Pull request by azizbohra**
i have added click_action parameter, which is required by ionic [FCM](https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated) plugin to handle the push when app is in the background mode. Although click_action parameter is optional, you can use as per your requirement.

please merge it as soon as possible so that we can use it in our projects
thanks to all the contributors for such an amazing library

### CODE REVIEW

**Comment by AndyGaskell** [comment]
Hi @azizbohra 

Thanks for the PR.  I'm not so familiar with ionic, but can this be done using a addData?

We do this with addData, which works well in flutter.  So, something like...
`$notification->addData("click_action", ".MainActivity");`
...or...
`$notification->addData("click_action", "FLUTTER_NOTIFICATION_CLICK");`

Or, for a bit more context,...
```
# Load composer
require 'vendor/autoload.php';
# set up the client
$client = new \Fcm\FcmClient($serverKey, $senderId);
# set up the notification
$notification = new \Fcm\Push\Notification();
$notification->addRecipient($recipients_id_array);
$notification->setTitle("hello, this is the title");
$notification->setBody("hello, this is the body");
$notification->addData("click_action", ".MainActivity");
# send the push
$response = $client->send($notification);
```

**Comment by azizbohra** [comment]
Hi, @AndyGaskell 

thanks for the reply
IONIC woks on Apache Cordova framework
I am using this [plugin](https://github.com/fechanique/cordova-plugin-fcm) to configure push notification on my app
the php package just works perfectly but if i want to get the on tap event when app is in background then i have to send `"click_action": "FCM_PLUGIN_ACTIVITY"` key in the notification object, it won't work if i send it in data object

i am sharing the plugin link [here](https://github.com/fechanique/cordova-plugin-fcm#send-notification-payload-example-rest-api) for your reference

`//POST: https://fcm.googleapis.com/fcm/send
//HEADER: Content-Type: application/json
//HEADER: Authorization: key=AIzaSy*******************
{
  "notification":{
    "title":"Notification title",
    "body":"Notification body",
    "sound":"default",
    "click_action":"FCM_PLUGIN_ACTIVITY",
    "icon":"fcm_push_icon"
  },
  "data":{
    "param1":"value1",
    "param2":"value2"
  },
    "to":"/topics/topicExample",
    "priority":"high",
    "restricted_package_name":""
}
//sound: optional field if you want sound with the notification
//click_action: must be present with the specified value for Android
//icon: white icon resource name for Android >5.0
//data: put any "param":"value" and retreive them in the JavaScript notification callback
//to: device token or /topic/topicExample
//priority: must be set to "high" for delivering notifications on closed iOS apps
//restricted_package_name: optional field if you want to send only to a restricted app package (i.e: com.myapp.test)`



kindly accept my pull request asap, so that we can integrate this package in our backend services

**Comment by azizbohra** [comment]
@AndyGaskell 

reminder
Plz take necessary action asap

**Comment by rolinger** [comment]
@azizbohra - I have an ionic v1 app and as Andy pointed out above you can add whatever you want to the data payload using the `addData` call.  I use cordova-plugin-firebasex and it has different requirements for passing payloads in that IT understands, but simply adding via the addData call is the way to do it:

```
$notification->addData("myCustom1", "value1");
$notification->addData("click_action", ".MainActivity");
$notification->addData("myCustom2", "value2");
```

This essentially creates a payload data object:
```
var payloadData : {
   "myCustom1" : "value1",
   "click_action" : ".MainActivity",
   "myCustom2" : "value2" 
}
```

**Comment by AndyGaskell** [comment]
Thanks @rolinger I wasn't really sure how this was implemented in Ionic

**Comment by azizbohra** [comment]
Hi every one, @AndyGaskell @rolinger 
I understand your point but try to understand my point of view
ionic 1 is pretty old now, i am talking about ionic 5 
in ionic 5 if i want to get onTap event of notification then i have to set click_action in notification payload not in data payload
plz try to understand what i mean
i know i can add any data using `$notification->addData("click_action", ".MainActivity");` but i can not because it will no going to work
i gave you all the evidence plz consider my request

Screen Shot 2020-10-07 at 11 13 52 AM

**Comment by rolinger** [comment]
After looking at the FCM docs, this isn't a Ionic issue, its a FCM thing.  `click_action` is a notification payload object - though it could be in the data payload, I can see where it would cause issues for those that need it in the notification payload (I think).

@azizbohra - @AndyGaskell 

I will see what I can do in the next two weeks to get it added to the base notification payload, unless @AndyGaskell you could get it added.  I won't have the time.

**Comment by azizbohra** [comment]
@rolinger 
thanks for your efforts
this is what i was trying to explain you
in order to listen for the onTap event of the notification in IONIC, the `click_action ` should be a part of notification object not the data object
i think now everything is clear 
plz merge the pull request asap
thanks

**Comment by AndyGaskell** [comment]
Hi @azizbohra 

Sorry for the confusion with this.  I think I understand the change now.

Could you make some changes to your PR please, then it will be easier to merge it.  Most of these would just be to tidy up things really.

1. Can you remove the un-necessary change to the .gitignore file?
2. Can you remove all the un-necessary white space changes in Notification.php?
3. Can you remove the new parameter from the __construct function in Notification.php.  Is it right that it would work fine for you just using the `setClickAction` function?
4. Can you write a test for it?  At the moment the PR reduces the packages test coverage.  I can do this if you like, if you're not familiar with unit test code.

I think with these changes, I'd be happy to test and merge this PR. Does that sound ok @rolinger ?

**Comment by azizbohra** [comment]
Hi, 

as per your request, i have done all the work, kindly check 

1. removed all the un-necessary change in the .gitignore file
2. removed all the un-necessary white space from the Notification.php file
3. wrote a new test case for click_action

Thanks @AndyGaskell @rolinger

**Comment by AndyGaskell** [comment]
Thanks @azizbohra I'll test it all today or tomorrow and get it merged

**Pull request merged**
