### PR TITLE
Merge rolinger/php-fcm fork

### PR DESCRIPTION
**Pull request by rolinger**
* Added support for: setIcon, setColor, setSound, setBadge, setTag, setSubtitle
* Added support for addDataArray for notifications
     differentiates between addData("key","value) and new addDataArray($myArray)
* Updated docs with iOS/Android notification options
* Updated docs providing more clarity on sending to deviceIDs vs Topics and the expected responses from each.
* Updated docs with Notification DATA options and explanations/examples

### CODE REVIEW

**Comment by rolinger** [comment]
Added support for: setIcon, setColor, setSound, setBadge, setTag, setSubtitle
Updated docs with iOS/Android notification options
Updated docs providing more clarity on sending to deviceIDs vs Topics and the expected responses from each

**Comment by rolinger** [comment]
What does this mean?  The continuous-integration/travis-ci/pr build failed?

**Comment by AndyGaskell** [comment]
Hi @rolinger 
Looking at the travis log, the error...

`Fatal error: Class Fcm\Push\Notification contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Fcm\Request::getUrl) in /home/travis/build/EdwinHoksberg/php-fcm/src/Push/Notification.php on line 8`

I would take a guess that it needs the...

`use Push;`

...line added back in.

So, from...
```class Notification implements Request
{
    
    /**
     * @var string
     */
    private $title;```
...to...
```class Notification implements Request
{
    use Push;
    /**
     * @var string
     */
    private $title;```
...but that is just a guess really.

**Comment by rolinger** [comment]
@AndyGaskell  - Andy what are your comments referring to?  Not certain because your response seems out of order or isn't attached the original thread.  Never seen this from github before.

**Comment by AndyGaskell** [comment]
Hi @rolinger 

I think github puts CI/CD bits at the bottom of the PR thread.

I was replying to your note on the 31 Jul 2019 saying...
> What does this mean? The continuous-integration/travis-ci/pr build failed?

Which made me think you were not sure about the reason for the...
> All checks have failed
> 1 failing check
> continuous-integration/travis-ci/pr — The Travis CI build failed 
...comment from the CI/CD job.

You PR looks good, just seems like the travis-ci check failed.  I was thinking it was because of the missing `use Push;` but I'm not sure really.

**Comment by rolinger** [comment]
@AndyGaskell - I see what you are referring to now.  However, I don't know what the issue is.  Its pointing to line 8 of src/push/Notification.php  `class Notification implements Request`.

How can this be resolved?  As well.  Since I have never managed a repo before I might need a little assistance.  I see you forked my fork, do I need to merge yours into mine before mine can be merged into the original?  Since we are both collaborators now can you just merge your fork into mine and then into the main...or must we still manage our own individual forks and then can only collaborate on the main.

**Comment by rolinger** [comment]
@AndyGaskell  Sorry, must not have had enough cofffee - for the new year yet.  I reread things more carefully and with your comment above added `use Push ;` back into the Notification.php file.  the travis-ci check made it past that error but is now giving a new one.  

It's now failing on:  
```
Notification
 [ ] It generates a correct notification object
```
but not certain why yet.  thoughts?

**Comment by rolinger** [comment]
@AndyGaskell - I think its failing travis-ci checks now because of some of the custom addDataArray vs the addData code I added.  trying to work through it now.

**Comment by rolinger** [comment]
@AndyGaskell ok, I am at a loss on the new error.  I moved the addDataArray() over to the main Push.php file and restored the Notification,php $data handling portion to the original.  Keeping the "addXXXXX" elements in Push.php and leaving on "setYYYY" to the Notification.php file.  However the travis-ci check is still failing on the Notification.php file - failing to create a proper object.    Can you take a look at my fork and tell me what you see.

**Comment by EdwinHoksberg** [comment]
@rolinger You can try to run the tests locally, but without the `--testdox` flag. That flag is only to nicely format the output but it sometimes hides any errors that may have occurred!

**Comment by AndyGaskell** [comment]
I'll have a look just now

**Comment by rolinger** [comment]
@AndyGaskell - yeah, haven't looked at it since 12 days ago.  Worked on it for a few hours, got frustrated - then busy and haven't come back to it yet.  Let me know what you find.  Prob some stupid overlook.

**Comment by AndyGaskell** [comment]
Hi @rolinger 

Looking at the Travis output at... 
https://travis-ci.org/EdwinHoksberg/php-fcm/jobs/637604783?utm_medium=notification&utm_source=github_status 
...I think it is failing a php-unti test, can see the output...
`vendor/bin/phpunit -c phpunit.dist.xml --testdox
PHPUnit 6.5.7 by Sebastian Bergmann and contributors.
FcmClient
 [x] It generates a correct guzzle client object
 [x] It correctly sends a request and parses the response
 [x] It throws an exception if invalid json was returned
 [x] It fails when calling a nonexisting magic method
Create
 [x] It generates a correct devicegroup create object
 [x] It can create a group from multiple devices
 [x] It can generate a quick object from magic method
Remove
 [x] It generates a correct devicegroup remove object
 [x] It can update a group with multiple devices
 [x] It can generate a quick object from magic method
Update
 [x] It generates a correct devicegroup update object
 [x] It can update a group with multiple devices
 [x] It can generate a quick object from magic method
Info
 [x] It generates a correct info request
 [x] It can generate a quick object from magic method
Data
 [x] It generates a correct data object
 [x] It can not have no recipients or topics
 [x] It can not have a recipient and topic
 [x] It should always have data parameters
 [x] It can generate a data push for multiple recipients
 [x] It can generate a data push for multiple topics
 [x] It can generate a data push with data
 [x] It can generate a quick object from magic method
Notification
 [ ] It generates a correct notification object
Generating code coverage report in Clover XML format ... done
The command "vendor/bin/phpunit -c phpunit.dist.xml --testdox" exited with 1.`

Which is, I think, the test...
`it_generates_a_correct_notification_object`
...in...
`tests/PushTests/NotificationTest.php`

I'll try and fix it though.

**Comment by rolinger** [comment]
@AndyGaskell - yeah, I saw all that, just couldn't figure out what was causing an invalid notification object.

**Comment by AndyGaskell** [comment]
Yea, running php unit locally I get...
```
1) NotificationTest::it_generates_a_correct_notification_object
Failed asserting that Array &0 (
    'to' => 'device_1'
    'notification' => Array &1 (
        'title' => 'Test title'
        'body' => 'A small body as an example'
        'sound' => ''
        'icon' => ''
        'color' => ''
        'tag' => ''
        'subtitle' => ''
    )
    'data' => Array &2 (
        'key' => 'value'
    )
) is identical to Array &0 (
    'to' => 'device_1'
    'data' => Array &1 (
        'key' => 'value'
    )
    'notification' => Array &2 (
        'title' => 'Test title'
        'body' => 'A small body as an example'
    )
).

/home/andy/php-fcm/rolinger-php-fcm/tests/PushTests/NotificationTest.php:26
```

So I'll adjust the test to match the new object format.

**Comment by rolinger** [comment]
...and while trying to fix it we will need to see if some of my changes caused more problems or not.  My big changes were moving the "addXXX" functions to `push.php` and keeping just the "setYYYY" functions in `notification.php`.

**Comment by AndyGaskell** [comment]
ok, I'll have a look at that while I'm there :)

**Comment by rolinger** [comment]
Thats weird, was the `data => [ ]` being set twice or did you just move to after `notification => [ ] ` ??

**Comment by AndyGaskell** [comment]
I just moved the data, sorry, that was a bit confusing.  It would have passed the obj match check, without moving it, but it seemed easier to read if the elements were all in the same place.

The tests seem to be getting further now, so that's good.  The log now says...

```
vendor/bin/phpunit -c phpunit.dist.xml --testdox
PHPUnit 6.5.7 by Sebastian Bergmann and contributors.
FcmClient
 [x] It generates a correct guzzle client object
 [x] It correctly sends a request and parses the response
 [x] It throws an exception if invalid json was returned
 [x] It fails when calling a nonexisting magic method
Create
 [x] It generates a correct devicegroup create object
 [x] It can create a group from multiple devices
 [x] It can generate a quick object from magic method
Remove
 [x] It generates a correct devicegroup remove object
 [x] It can update a group with multiple devices
 [x] It can generate a quick object from magic method
Update
 [x] It generates a correct devicegroup update object
 [x] It can update a group with multiple devices
 [x] It can generate a quick object from magic method
Info
 [x] It generates a correct info request
 [x] It can generate a quick object from magic method
Data
 [x] It generates a correct data object
 [x] It can not have no recipients or topics
 [x] It can not have a recipient and topic
 [x] It should always have data parameters
 [x] It can generate a data push for multiple recipients
 [x] It can generate a data push for multiple topics
 [x] It can generate a data push with data
 [x] It can generate a quick object from magic method
Notification
 [x] It generates a correct notification object
 [x] It can not have no recipients or topics
 [x] It can not have a recipient and topic
 [ ] It can generate a notification for multiple recipients
Generating code coverage report in Clover XML format ... done
The command "vendor/bin/phpunit -c phpunit.dist.xml --testdox" exited with 2.
Done. Your build exited with 1.
```

...so I'll look at that new error now.

**Comment by rolinger** [comment]
@AndyGaskell - whats weird with all these errors is that I am able to use the code in my project without issue.  Been using it for sometime now.  Never noticed an issue or had any errors.  Thanks for diving into it...I am in the weeds these last few weeks on a deadline and haven't had much time or energy to look at it.

**Comment by AndyGaskell** [comment]
These errors are from the unit tests, so they're not really errors, just unit tests flagging failing.  In the most part, the fails are because the notification object doesn't look like what the text expected.  Mainly because the "sound", "icon", "color", "tag" and "subtitle" elements have been added in the PR.

**Comment by rolinger** [comment]
Ah, ok...makes more sense now.  I have never maintained a public project before so I haven't ever gone through all the official github validations to merge projects and what not.  Some of this stuff is new to me.

**Comment by AndyGaskell** [comment]
No worries, with your deadline, really happy to look at it and help.

I've pretty much fixed all of the tests now here, the only issue is, in the `getBody` function in `Notification.php` in that it checks for data not being empty, with the...

```
if ( empty($this->data)) {
    throw new NotificationException('Data should not be empty for a Data Notification.');
}
```

...code.  This means a notification object can't be created if there is no data.  This is a good check, but probably a backwards breaking change.  I'll have a think about a different way to make that sort of check.

The change was in...
https://github.com/EdwinHoksberg/php-fcm/pull/11/commits/621248315b369d9f12aeb880da9fb9f11df8c25a

**Comment by AndyGaskell** [comment]
So, I'm not sure, long term, what the best option is for this `Data should not be empty for a Data Notification.` check in the `getBody` function.  I've commented it out just now, that means we'll be able to get this PR merged in.

Automated tests on pull requests in github are cool, really nice, but it's a bit of overhead work to keep the php unit test up-to-date with code changes.

**Comment by rolinger** [comment]
I will take a look at it too, prob by end of week.  I am thinking it should be more of a IF data exists add it, otherwise don't add the `data => [ ]` field.

**Comment by AndyGaskell** [comment]
So, I think it should all merge ok into.

I wrote a few more unit tests, because the coverage went down.  Just tried to commit push them and got an error...

```
git push origin master
Enumerating objects: 17, done.
Counting objects: 100% (17/17), done.
Delta compression using up to 4 threads
Compressing objects: 100% (10/10), done.
Writing objects: 100% (10/10), 1.99 KiB | 1.99 MiB/s, done.
Total 10 (delta 6), reused 0 (delta 0)
remote: Resolving deltas: 100% (6/6), completed with 5 local objects.
To github.com:rolinger/php-fcm.git
 ! [remote rejected] master -> master (permission denied)
error: failed to push some refs to 'git@github.com:rolinger/php-fcm.git'
```

...I'm not sure what this means, and it was working earlier.  Sorry if this is because you changed permissions thinking I was perhaps changing too many things in a bit of a rush.

**Comment by AndyGaskell** [comment]
ah, sorry, just realised it was probably because you merged the branch back into EdwinHoksberg:master 

That's cool, great to get all your new features back into the master, thanks :)

**Pull request merged**
