### PR TITLE
Update Notification.php

### PR DESCRIPTION
**Pull request by rayansys**
add android_channel_id

### CODE REVIEW

**Comment by AndyGaskell** [comment]
There is discussion re this on...
 Android Notification channel id #29

**Review by rolinger — APPROVED** [review]

**Comment by rolinger** [comment]
@rayansys - it looks like your changes are in conflict.  Can you please resolve?

While adding for the android_id it seems you deleted code for $click_action and $image_url

**Comment by rolinger** [comment]
This has been merged from a patch branch https://github.com/EdwinHoksberg/php-fcm/tree/rayansys-patch-1

**Comment by rolinger** [comment]
closing.

**Pull request closed without merging**
