### PR TITLE
Add Push::setCollapseKey() and ::setPriority()

### LINKED ISSUE #57: Missing collapse key
See docs: https://firebase.google.com/docs/cloud-messaging/concept-options#delivery-options

And another PHP implementation: https://github.com/Paragraph1/php-fcm/blob/b8d6fec2c5327ed8fbe09d4d1cc0b53467a340e0/src/Message.php#L151

### PR DESCRIPTION
**Pull request by Philipp91**
Fixes #57 and #48.

Note that this PR ist rebased on top of #59, so need to merge that one first.

### CODE REVIEW

**Comment by AndyGaskell** [comment]
Hi @rolinger 
Did you have a look at this PR?  There is quite a lot going on, but I think it looks ok.

**Comment by rolinger** [comment]
I have not.  Haven't had the time for quite some while now.  Feverishly getting new version of my app completed to meet some client needs coming up this month.

**Comment by rolinger** [comment]
If your good with it go ahead and merge.

**Comment by rolinger** [comment]
This is last PR merge before enhancement to update repo for FCM HTTPv1

**Pull request merged**
